/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaca1.BACKEND;

/**
 *
 * @author Gabriel Kuek
 */


import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class createPanel extends javax.swing.JFrame {

    // Declare components
    private JLabel textLabel;
    private JTextField textField;
    private JButton createButton;
    
    // Declare components for the student form
    private JLabel nameLabel;
    private JTextField nameInput;
    private JLabel adminLabel;
    private JTextField adminInput;
    private JLabel classLabel;
    private JTextField classInput;

    // Declare components for the module form
    private JLabel moduleAdminNumberLabel;
    private JTextField moduleAdminNumberInput;
    private JLabel moduleCodeLabel;
    private JTextField moduleCodeInput;
    private JLabel moduleNameLabel;
    private JTextField moduleNameInput;
    private JLabel moduleMarksLabel;
    private JTextField moduleMarksInput;
    private JLabel moduleCreditUnitLabel;
    private JTextField moduleCreditUnitInput;
    
    // hashmap key
    private String currentKey = "";

    // hashmap of actions
    HashMap<String, ActionListener> actions = new HashMap<>();
    
    /**
     * Creates new form createPanel
     */
    public createPanel() {
        initComponents();
//        initContentPanel();
        initActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // define actions
    private void initActions() {
        // create student action
        actions.put("createStudent", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // create student object from name, adminNo, class
                String tempName = nameInput.getText();
                String tempAdmin = adminInput.getText();
                String tempClass = classInput.getText();
                Student tempStudent = new Student(tempName, tempAdmin, tempClass);
                
                // push student object into StudentManagement.students array
                arrayUtils.pushStudent(tempStudent);
                
                // write into student.txt
                TxtFileWriter.writeStudents();
//                System.out.println("student test");
            }
        });

        // add module to Student action
        actions.put("addModule", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // create module with given information
                String tempModuleAdminNumber = moduleAdminNumberInput.getText();
                String tempModuleCode = moduleCodeInput.getText();
                String tempModuleName = moduleNameInput.getText();
                double tempModuleMarks = Double.parseDouble(moduleMarksInput.getText());
                int tempModuleCreditUnit = Integer.parseInt(moduleCreditUnitInput.getText());
                
                int iterations = 0;
                
                iterations = 0;
                
                for (Student student : StudentManagement.students) {
                    System.out.println(student.getAdminNo().equals(tempModuleAdminNumber));
                    if (student.getAdminNo().equals(tempModuleAdminNumber)) {
                        break;
                    }

                    iterations++;
                }

                if (iterations == StudentManagement.students.length) {
                    JOptionPane.showMessageDialog(null, 
                            "No student with admin number of " + tempModuleAdminNumber + " exists. Please try again.",
                            "No Student Found",
                            JOptionPane.ERROR_MESSAGE);

                    return;
                }
                
                Module tempModule = new Module(tempModuleCode, tempModuleName, tempModuleCreditUnit, tempModuleMarks);


                StudentManagement.students[iterations].setModules_taken(
                        arrayUtils.appendModuleElement(
                                StudentManagement.students[iterations].getModules_Taken(), 
                                tempModule
                        )
                );
                
                // update student.txt
                TxtFileWriter.writeStudents();
//                System.out.println("module");
            }
        });
    }
    
//    private void initContentPanel() {
//        
//        // add components
//        JLabel nameLabel = new JLabel("Name: ");
//        JTextField nameInput = new JTextField();
//        JLabel adminLabel = new JLabel("Admin no: ");
//        JTextField adminInput = new JTextField();
//        JLabel classLabel = new JLabel("Class: ");
//        JTextField classInput = new JTextField();
//        
//        contentPanel.add(nameLabel);
//        contentPanel.add(nameInput);
//        contentPanel.add(adminLabel);
//        contentPanel.add(adminInput);
//        contentPanel.add(classLabel);
//        contentPanel.add(classInput);
//        
//        // apply changes
//        contentPanel.revalidate();
//        contentPanel.repaint();
//    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        topNav = new javax.swing.JPanel();
        content1 = new javax.swing.JPanel();
        form1 = new javax.swing.JPanel();
        createHeader1 = new javax.swing.JPanel();
        functionTitle = new javax.swing.JLabel();
        createContent = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        sideNav = new javax.swing.JPanel();
        dashboardSideNav = new javax.swing.JButton();
        createStudentSideNav = new javax.swing.JButton();
        createModuleSideNav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(49, 54, 63));

        topNav.setBackground(new java.awt.Color(34, 40, 49));
        topNav.setPreferredSize(new java.awt.Dimension(785, 50));

        javax.swing.GroupLayout topNavLayout = new javax.swing.GroupLayout(topNav);
        topNav.setLayout(topNavLayout);
        topNavLayout.setHorizontalGroup(
            topNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        topNavLayout.setVerticalGroup(
            topNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        content1.setOpaque(false);

        form1.setBackground(new java.awt.Color(217, 217, 217));
        form1.setMinimumSize(new java.awt.Dimension(263, 100));
        form1.setLayout(new javax.swing.BoxLayout(form1, javax.swing.BoxLayout.Y_AXIS));

        createHeader1.setBackground(new java.awt.Color(34, 40, 49));
        createHeader1.setMinimumSize(new java.awt.Dimension(263, 0));
        createHeader1.setPreferredSize(new java.awt.Dimension(263, 50));

        functionTitle.setBackground(new java.awt.Color(243, 243, 243));
        functionTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        functionTitle.setForeground(new java.awt.Color(243, 243, 243));
        functionTitle.setText("Create Student");

        javax.swing.GroupLayout createHeader1Layout = new javax.swing.GroupLayout(createHeader1);
        createHeader1.setLayout(createHeader1Layout);
        createHeader1Layout.setHorizontalGroup(
            createHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(createHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createHeader1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(functionTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        createHeader1Layout.setVerticalGroup(
            createHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(createHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createHeader1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(functionTitle)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        form1.add(createHeader1);

        createContent.setOpaque(false);
        createContent.setPreferredSize(new java.awt.Dimension(263, 300));

        contentPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));

        submitButton.setBackground(new java.awt.Color(118, 171, 174));
        submitButton.setForeground(new java.awt.Color(243, 243, 243));
        submitButton.setText("Create");
        submitButton.setBorder(null);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout createContentLayout = new javax.swing.GroupLayout(createContent);
        createContent.setLayout(createContentLayout);
        createContentLayout.setHorizontalGroup(
            createContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createContentLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(createContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        createContentLayout.setVerticalGroup(
            createContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createContentLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(createContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        form1.add(createContent);

        javax.swing.GroupLayout content1Layout = new javax.swing.GroupLayout(content1);
        content1.setLayout(content1Layout);
        content1Layout.setHorizontalGroup(
            content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, content1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(form1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content1Layout.setVerticalGroup(
            content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        sideNav.setBackground(new java.awt.Color(34, 40, 49));

        dashboardSideNav.setText("Dashboard");
        dashboardSideNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardSideNavMouseClicked(evt);
            }
        });

        createStudentSideNav.setText("Create Student");
        createStudentSideNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createStudentSideNavMouseClicked(evt);
            }
        });

        createModuleSideNav.setText("Create Module");
        createModuleSideNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createModuleSideNavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideNavLayout = new javax.swing.GroupLayout(sideNav);
        sideNav.setLayout(sideNavLayout);
        sideNavLayout.setHorizontalGroup(
            sideNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNavLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(sideNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardSideNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createStudentSideNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createModuleSideNav, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideNavLayout.setVerticalGroup(
            sideNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNavLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dashboardSideNav)
                .addGap(18, 18, 18)
                .addComponent(createStudentSideNav)
                .addGap(18, 18, 18)
                .addComponent(createModuleSideNav)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topNav, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(content1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundLayout.createSequentialGroup()
                    .addComponent(sideNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 626, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(topNav, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addComponent(sideNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardSideNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardSideNavMouseClicked
        // TODO add your handling code here:
        StudentAdminSystemView studentDisplay = new StudentAdminSystemView();
        studentDisplay.show();
        
        dispose();
    }//GEN-LAST:event_dashboardSideNavMouseClicked

    // create student
    private void createStudentSideNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createStudentSideNavMouseClicked
        // TODO add your handling code here:
        // set header text
        functionTitle.setText("Create Student");
        
        // set submit button text
        submitButton.setText("Create");
        
        // config global key
        currentKey = "createStudent";
        
        // clear form
        contentPanel.removeAll();
        contentPanel.repaint();
        
        // add components
        nameLabel = new JLabel("Name: ");
        nameInput = new JTextField();
        adminLabel = new JLabel("Admin no: ");
        adminInput = new JTextField();
        classLabel = new JLabel("Class: ");
        classInput = new JTextField();
        
        contentPanel.add(nameLabel);
        contentPanel.add(nameInput);
        contentPanel.add(adminLabel);
        contentPanel.add(adminInput);
        contentPanel.add(classLabel);
        contentPanel.add(classInput);
        
        // apply changes
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_createStudentSideNavMouseClicked

    // create module
    private void createModuleSideNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createModuleSideNavMouseClicked
        // TODO add your handling code here:
        // set header text
        functionTitle.setText("Create Module for Student");
        
        // set submit button text
        submitButton.setText("Add");
        
        // config global key
        currentKey = "addModule";
        
        // clear form
        contentPanel.removeAll();
        contentPanel.repaint();
        
        // add components
        moduleAdminNumberLabel = new JLabel("Student Admin Number: ");
        moduleAdminNumberInput = new JTextField();
        moduleCodeLabel = new JLabel("Module Code: ");
        moduleCodeInput = new JTextField();
        moduleNameLabel = new JLabel("Module Name: ");
        moduleNameInput = new JTextField();
        moduleMarksLabel = new JLabel("Marks: ");
        moduleMarksInput = new JTextField();
        moduleCreditUnitLabel = new JLabel("Credit Unit: ");
        moduleCreditUnitInput = new JTextField();
        
        contentPanel.add(moduleAdminNumberLabel);
        contentPanel.add(moduleAdminNumberInput);
        contentPanel.add(moduleCodeLabel);
        contentPanel.add(moduleCodeInput);
        contentPanel.add(moduleNameLabel);
        contentPanel.add(moduleNameInput);
        contentPanel.add(moduleMarksLabel);
        contentPanel.add(moduleMarksInput);
        contentPanel.add(moduleCreditUnitLabel);
        contentPanel.add(moduleCreditUnitInput);
        
        // apply changes
        contentPanel.revalidate();
        contentPanel.repaint();
    }//GEN-LAST:event_createModuleSideNavMouseClicked

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
        ActionListener action = actions.get(currentKey);
        if (action != null) {
            action.actionPerformed(new ActionEvent(this, ActionEvent.ACTION_PERFORMED, null));
        }    
    }//GEN-LAST:event_submitButtonMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JPanel content1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel createContent;
    private javax.swing.JPanel createHeader;
    private javax.swing.JPanel createHeader1;
    private javax.swing.JButton createModuleSideNav;
    private javax.swing.JButton createStudentSideNav;
    private javax.swing.JButton dashboardSideNav;
    private javax.swing.JPanel form;
    private javax.swing.JPanel form1;
    private javax.swing.JLabel functionTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel sideNav;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel topNav;
    // End of variables declaration//GEN-END:variables
}
