/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaca1.BACKEND;

/**
 *
 * @author Darren
 */
public class StudentEnquiryLecturerSystem extends javax.swing.JFrame {

    /**
     * Creates new form StudentEnquiryLecturerSystem
     */
    public StudentEnquiryLecturerSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        panelForTitle = new javax.swing.JPanel();
        lblForTitle = new javax.swing.JLabel();
        panelForSearch = new javax.swing.JPanel();
        radioButtonForName = new javax.swing.JRadioButton();
        radioButtonForClass = new javax.swing.JRadioButton();
        radioButtonForAdminNo = new javax.swing.JRadioButton();
        buttonForSearch = new javax.swing.JButton();
        buttonForNext = new javax.swing.JButton();
        buttonForPrevious = new javax.swing.JButton();
        textFieldForSearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        panelForResults = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaForResults = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 54, 63));

        jPanel1.setBackground(new java.awt.Color(49, 54, 63));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        panelForTitle.setBackground(new java.awt.Color(34, 40, 49));
        panelForTitle.setPreferredSize(new java.awt.Dimension(791, 80));

        lblForTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblForTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForTitle.setText("Student Enquiry System");

        javax.swing.GroupLayout panelForTitleLayout = new javax.swing.GroupLayout(panelForTitle);
        panelForTitle.setLayout(panelForTitleLayout);
        panelForTitleLayout.setHorizontalGroup(
            panelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
            .addGroup(panelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelForTitleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblForTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelForTitleLayout.setVerticalGroup(
            panelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(panelForTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelForTitleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblForTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel1.add(panelForTitle);

        panelForSearch.setBackground(new java.awt.Color(49, 54, 63));
        panelForSearch.setMinimumSize(new java.awt.Dimension(791, 100));
        panelForSearch.setPreferredSize(new java.awt.Dimension(791, 110));
        panelForSearch.setLayout(new java.awt.GridBagLayout());

        radioButtonForName.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonForName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        panelForSearch.add(radioButtonForName, gridBagConstraints);

        radioButtonForClass.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonForClass.setText("Class");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        panelForSearch.add(radioButtonForClass, gridBagConstraints);

        radioButtonForAdminNo.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonForAdminNo.setText("Admin No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 40);
        panelForSearch.add(radioButtonForAdminNo, gridBagConstraints);

        buttonForSearch.setBackground(new java.awt.Color(34, 40, 49));
        buttonForSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonForSearch.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        panelForSearch.add(buttonForSearch, gridBagConstraints);

        buttonForNext.setBackground(new java.awt.Color(34, 40, 49));
        buttonForNext.setForeground(new java.awt.Color(255, 255, 255));
        buttonForNext.setText("Next");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForSearch.add(buttonForNext, gridBagConstraints);

        buttonForPrevious.setBackground(new java.awt.Color(34, 40, 49));
        buttonForPrevious.setForeground(new java.awt.Color(255, 255, 255));
        buttonForPrevious.setText("Prev");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelForSearch.add(buttonForPrevious, gridBagConstraints);

        textFieldForSearch.setBackground(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelForSearch.add(textFieldForSearch, gridBagConstraints);

        jPanel1.add(panelForSearch);

        jPanel4.setBackground(new java.awt.Color(49, 54, 63));
        jPanel4.setPreferredSize(new java.awt.Dimension(1582, 350));

        panelForResults.setBackground(new java.awt.Color(49, 54, 63));
        panelForResults.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panelForResults.setForeground(new java.awt.Color(204, 204, 204));

        textAreaForResults.setEditable(false);
        textAreaForResults.setColumns(20);
        textAreaForResults.setRows(5);
        jScrollPane1.setViewportView(textAreaForResults);

        javax.swing.GroupLayout panelForResultsLayout = new javax.swing.GroupLayout(panelForResults);
        panelForResults.setLayout(panelForResultsLayout);
        panelForResultsLayout.setHorizontalGroup(
            panelForResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelForResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelForResultsLayout.setVerticalGroup(
            panelForResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelForResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelForResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEnquiryLecturerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEnquiryLecturerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEnquiryLecturerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEnquiryLecturerSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEnquiryLecturerSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonForNext;
    private javax.swing.JButton buttonForPrevious;
    private javax.swing.JButton buttonForSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblForTitle;
    private javax.swing.JPanel panelForResults;
    private javax.swing.JPanel panelForSearch;
    private javax.swing.JPanel panelForTitle;
    private javax.swing.JRadioButton radioButtonForAdminNo;
    private javax.swing.JRadioButton radioButtonForClass;
    private javax.swing.JRadioButton radioButtonForName;
    private javax.swing.JTextArea textAreaForResults;
    private javax.swing.JTextField textFieldForSearch;
    // End of variables declaration//GEN-END:variables
}
